// ============================================================================
// FILE: apb_master_monitor.sv
// DESCRIPTION:
//   The Monitor for the APB Master Bridge testbench.
//
//   The monitor is a PASSIVE observer — it watches the APB bus signals
//   coming out of the DUT and captures completed transfers.
//
//   A transfer is "complete" when PENABLE=1 AND PREADY=1 simultaneously.
//   This is the APB protocol's handshake in the ACCESS phase.
//
//   KEY DIFFERENCE FROM SLAVE TB:
//   In the slave TB, the monitor watched inputs being driven TO the slave.
//   Here, the monitor watches OUTPUTS generated BY the master DUT
//   to verify it correctly translates system requests into APB protocol.
//
//   DATA FLOW:
//   Monitor observes DUT outputs → creates seq_item → broadcasts via ap
//   → Scoreboard receives and checks
// ============================================================================

// Extends uvm_monitor, which is a base class for passive observation components.
// Unlike uvm_driver, monitors should never drive signals.
class apb_master_monitor extends uvm_monitor;

  // Register with UVM factory for factory creation and overrides.
  `uvm_component_utils(apb_master_monitor)

  // Handle to the virtual interface (for reading APB bus signals).
  virtual apb_master_if vif;

  // Analysis port: a broadcast mechanism for sending observed transactions
  // to any connected subscriber (typically the scoreboard).
  // "analysis_port" is a one-to-many connection — multiple subscribers
  // can connect to it simultaneously. When we call ap.write(item),
  // all connected subscribers receive a copy of the item.
  uvm_analysis_port #(apb_master_seq_item) ap;

  // ---- Constructor ----
  function new(string name = "apb_master_monitor", uvm_component parent);
    super.new(name, parent);
  endfunction

  // ---- Build Phase ----
  // Create the analysis port and get the virtual interface handle.
  function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    // Create the analysis port instance.
    // "ap" is the port name, "this" is the parent component.
    ap = new("ap", this);

    // Retrieve virtual interface from config_db (stored by tb_top).
    if (!uvm_config_db #(virtual apb_master_if)::get(this, "", "vif", vif))
      `uvm_fatal("MON", "Could not get virtual interface 'vif' from config_db")
  endfunction

  // ---- Run Phase: Watch for completed APB transfers ----
  // This task runs for the entire simulation, sampling signals every clock cycle.
  task run_phase(uvm_phase phase);
    apb_master_seq_item item;  // Handle for the captured transaction

    forever begin
      // Wait for the next clock edge (using monitor clocking block).
      // The clocking block samples signals 1ns before the edge to avoid races.
      @(vif.monitor_cb);

      // ── Check for a completed APB transfer ──
      // In the APB protocol, a transfer completes in the ACCESS phase when
      // both PENABLE (master ready) and PREADY (slave ready) are high.
      if (vif.monitor_cb.PENABLE && vif.monitor_cb.PREADY) begin

        // Create a new transaction object to hold the observed values.
        // Using type_id::create enables factory overrides.
        item = apb_master_seq_item::type_id::create("item");

        // ── Capture APB bus signals (DUT outputs) ──
        // These are the signals the master DUT generated on the APB bus.
        item.paddr   = vif.monitor_cb.PADDR;             // Address on APB bus
        item.pwdata  = vif.monitor_cb.PWDATA;             // Write data on APB bus
        item.pwrite  = vif.monitor_cb.PWRITE;             // Write/read direction
        item.psel1   = vif.monitor_cb.PSEL1;              // Slave 1 selected?
        item.psel2   = vif.monitor_cb.PSEL2;              // Slave 2 selected?
        item.pslverr = vif.monitor_cb.PSLVERR;            // Any slave error?
        item.rdata   = vif.monitor_cb.apb_read_data_out;  // Read data from DUT

        // ── Derive driver-side fields from observed values ──
        // We reconstruct the driver-side fields for convenience.
        // The scoreboard uses these to check that the DUT translated
        // system inputs into correct APB outputs.
        item.addr  = vif.monitor_cb.PADDR;       // PADDR should match the input addr
        item.wdata = vif.monitor_cb.PWDATA;       // PWDATA should match the input wdata
        item.read  = ~vif.monitor_cb.PWRITE;      // APB convention: PWRITE=0 means read

        // Log the observed transaction
        `uvm_info("MON", $sformatf("Observed: %s", item.convert2string()), UVM_MEDIUM)

        // ── Broadcast to all connected subscribers ──
        // ap.write() sends this item to the scoreboard (and any other
        // component connected to this analysis port).
        ap.write(item);
      end
    end
  endtask

endclass
