// ============================================================================
// FILE: apb_master_monitor.sv
// DESCRIPTION:
//   The Monitor for the APB Master Bridge testbench.
//
//   It passively watches the APB bus outputs from the DUT and captures
//   completed transfers (when PENABLE=1 and PREADY=1).
//
//   KEY DIFFERENCE FROM SLAVE TB:
//   In the slave TB, the monitor watched inputs being driven TO the slave.
//   Here, the monitor watches OUTPUTS generated BY the master DUT
//   to verify it correctly translates system requests into APB protocol.
// ============================================================================

class apb_master_monitor extends uvm_monitor;

  `uvm_component_utils(apb_master_monitor)

  // Handle to the virtual interface
  virtual apb_master_if vif;

  // Analysis port: broadcasts observed transactions
  uvm_analysis_port #(apb_master_seq_item) ap;

  // ---- Constructor ----
  function new(string name = "apb_master_monitor", uvm_component parent);
    super.new(name, parent);
  endfunction

  // ---- Build Phase ----
  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    ap = new("ap", this);
    if (!uvm_config_db #(virtual apb_master_if)::get(this, "", "vif", vif))
      `uvm_fatal("MON", "Could not get virtual interface 'vif' from config_db")
  endfunction

  // ---- Run Phase: Watch for completed APB transfers ----
  task run_phase(uvm_phase phase);
    forever begin
      @(vif.monitor_cb);

      // A transfer is complete when PENABLE=1 AND PREADY=1
      if (vif.monitor_cb.PENABLE && vif.monitor_cb.PREADY) begin

        // Create a new transaction and fill in observed values
        apb_master_seq_item item = apb_master_seq_item::type_id::create("item");

        // Capture APB bus signals (DUT outputs)
        item.paddr   = vif.monitor_cb.PADDR;
        item.pwdata  = vif.monitor_cb.PWDATA;
        item.pwrite  = vif.monitor_cb.PWRITE;
        item.psel1   = vif.monitor_cb.PSEL1;
        item.psel2   = vif.monitor_cb.PSEL2;
        item.pslverr = vif.monitor_cb.PSLVERR;
        item.rdata   = vif.monitor_cb.apb_read_data_out;

        // Derive driver-side fields from observed values for convenience
        item.addr  = vif.monitor_cb.PADDR;       // PADDR should match input addr
        item.wdata = vif.monitor_cb.PWDATA;       // PWDATA should match input wdata
        item.read  = ~vif.monitor_cb.PWRITE;      // read = ~PWRITE (APB convention)

        `uvm_info("MON", $sformatf("Observed: %s", item.convert2string()), UVM_MEDIUM)

        // Broadcast to scoreboard
        ap.write(item);
      end
    end
  endtask

endclass
