// =============================================================================
// FILE: apb_if.sv
// DESCRIPTION:
//   APB Virtual Interface — the physical-to-virtual bridge between the static
//   RTL DUT (master_bridge) and the dynamic UVM class-based testbench.
//
//   This interface bundles ALL signals that flow between the testbench and the
//   DUT, organized into three categories:
//     1. System-side signals  — driven by the system agent to initiate transfers
//     2. APB bus signals      — generated by the DUT as outputs
//     3. Slave response signals — driven by the slave agent to complete handshakes
//
//   CLOCKING BLOCKS:
//     Clocking blocks provide cycle-accurate, race-free signal access by
//     automatically sampling inputs BEFORE the clock edge and driving outputs
//     AFTER the clock edge, with configurable skew (#1ns here).
//
//   MODPORTS:
//     Modports enforce strict directional access on each clocking block,
//     preventing accidental cross-driving between agents.
//
//   NOTE: This file intentionally omits UVM includes/imports. Including UVM
//   package imports at global scope before the interface declaration can cause
//   compiler parser errors (e.g. NOPBIND/NONAIF) on Cadence Xcelium.
// =============================================================================

interface apb_if (
  input logic PCLK,       // APB clock — 100 MHz (10ns period) generated by tb_top
  input logic PRESETn     // Active-low reset — 0=reset active, 1=normal operation
);

  // ---------------------------------------------------------------------------
  // SYSTEM-SIDE SIGNALS (driven by apb_sys_driver → consumed by DUT)
  // These represent the "host" or "processor" side of the master bridge.
  // The system tells the master WHAT transfer to perform.
  // ---------------------------------------------------------------------------
  logic [8:0] apb_write_paddr;   // 9-bit write address: bit[8]=slave select, bits[7:0]=offset
  logic [8:0] apb_read_paddr;    // 9-bit read address: bit[8]=slave select, bits[7:0]=offset
  logic [7:0] apb_write_data;    // 8-bit data payload for write operations
  logic       READ_WRITE;        // Transfer direction: 1=Read, 0=Write
  logic       transfer;          // Transfer request strobe: 1=initiate transfer, 0=idle
  logic [7:0] apb_read_data_out; // 8-bit data returned by DUT to system after read completes

  // ---------------------------------------------------------------------------
  // SLAVE RESPONSE SIGNALS (driven by apb_slv_driver → consumed by DUT)
  // These emulate the physical APB slave's response on the bus.
  // ---------------------------------------------------------------------------
  logic [7:0] PRDATA;    // Read data driven by slave back to master during read transfers
  logic       PREADY;    // Slave ready signal: 1=slave ready to complete transfer this cycle

  // ---------------------------------------------------------------------------
  // APB BUS SIGNALS (driven by DUT → sampled by monitors and slave driver)
  // These are the standard AMBA APB protocol signals generated by the master.
  // ---------------------------------------------------------------------------
  logic       PSEL1;     // Chip select for Slave 1 — asserted when PADDR[8]=0
  logic       PSEL2;     // Chip select for Slave 2 — asserted when PADDR[8]=1
  logic       PENABLE;   // APB enable — low during SETUP phase, high during ACCESS phase
  logic [8:0] PADDR;     // APB address bus — driven by master during SETUP phase
  logic       PWRITE;    // APB direction — 1=write transfer, 0=read transfer
  logic [7:0] PWDATA;    // APB write data bus — driven by master during write transfers
  logic       PSLVERR;   // Slave error flag — 1=transfer error detected by master logic

  // ---------------------------------------------------------------------------
  // CLOCKING BLOCK: master_cb
  // Used by: apb_sys_driver (system-side active driver)
  // Purpose: Drives system-side inputs to the DUT and samples DUT responses.
  //          The 1ns output skew ensures signals are stable before DUT samples them.
  //          The 1ns input skew ensures we sample DUT outputs after they settle.
  // ---------------------------------------------------------------------------
  clocking master_cb @(posedge PCLK);
    default input #1ns output #1ns;
    output transfer;            // Driver asserts transfer request
    output READ_WRITE;          // Driver sets read/write direction
    output apb_write_paddr;     // Driver provides write address
    output apb_read_paddr;      // Driver provides read address
    output apb_write_data;      // Driver provides write data
    input  apb_read_data_out;   // Driver samples read data returned by DUT
    input  PREADY;              // Driver polls for handshake completion
    input  PENABLE;             // Driver can observe protocol state
    input  PSLVERR;             // Driver captures error status
  endclocking

  // ---------------------------------------------------------------------------
  // CLOCKING BLOCK: slave_cb
  // Used by: apb_slv_driver (reactive slave driver)
  // Purpose: Samples the APB bus signals generated by the DUT to decide
  //          how to respond, and drives PREADY/PRDATA back to the DUT.
  // ---------------------------------------------------------------------------
  clocking slave_cb @(posedge PCLK);
    default input #1ns output #1ns;
    input  PSEL1;       // Slave sees which chip select the master asserted
    input  PSEL2;       // Slave sees which chip select the master asserted
    input  PENABLE;     // Slave detects SETUP (low) vs ACCESS (high) phase
    input  PADDR;       // Slave reads target address for memory operations
    input  PWRITE;      // Slave knows if this is a write (1) or read (0)
    input  PWDATA;      // Slave captures write data from the master
    output PREADY;      // Slave asserts readiness to complete the transfer
    output PRDATA;      // Slave drives read data back onto the bus
  endclocking

  // ---------------------------------------------------------------------------
  // CLOCKING BLOCK: sys_monitor_cb
  // Used by: apb_sys_monitor (passive system-side monitor)
  // Purpose: Passively samples system-side command signals to build "expected"
  //          transaction items for the scoreboard. All signals are inputs.
  // ---------------------------------------------------------------------------
  clocking sys_monitor_cb @(posedge PCLK);
    default input #1ns;
    input transfer;             // Monitor detects when a transfer is requested
    input READ_WRITE;           // Monitor captures the transfer direction
    input apb_write_paddr;      // Monitor captures the write address
    input apb_read_paddr;       // Monitor captures the read address
    input apb_write_data;       // Monitor captures the write data
    input apb_read_data_out;    // Monitor captures read data returned to system
    input PREADY;               // Monitor waits for handshake completion
  endclocking

  // ---------------------------------------------------------------------------
  // CLOCKING BLOCK: monitor_cb
  // Used by: apb_monitor (standalone APB bus monitor)
  // Purpose: Passively samples ALL APB bus signals to build "actual" transaction
  //          items for the scoreboard. Captures the completed handshake snapshot.
  // ---------------------------------------------------------------------------
  clocking monitor_cb @(posedge PCLK);
    default input #1ns;
    input PSEL1;        // Bus monitor sees which slave was selected
    input PSEL2;        // Bus monitor sees which slave was selected
    input PENABLE;      // Bus monitor detects ACCESS phase
    input PADDR;        // Bus monitor captures transaction address
    input PWRITE;       // Bus monitor captures transaction direction
    input PWDATA;       // Bus monitor captures write data on bus
    input PREADY;       // Bus monitor detects handshake completion
    input PRDATA;       // Bus monitor captures read data on bus
    input PSLVERR;      // Bus monitor captures error status
  endclocking

  // ---------------------------------------------------------------------------
  // MODPORTS — enforce directional access for each UVM component
  // ---------------------------------------------------------------------------
  modport master_mp (clocking master_cb, input PCLK, input PRESETn);      // For apb_sys_driver
  modport slave_mp  (clocking slave_cb,  input PCLK, input PRESETn);      // For apb_slv_driver
  modport sys_monitor_mp (clocking sys_monitor_cb, input PCLK, input PRESETn);  // For apb_sys_monitor
  modport monitor_mp (clocking monitor_cb, input PCLK, input PRESETn);    // For apb_monitor

endinterface
